== Development Guide

Requirements:

- Gradle 5.3 to build apiator plugin
- JDK 11 to build and test all Apiator modules
- Node.js 10 to develop Core Html Renderer

=== Core HTML renderer

The `package.json` is located in source root of html renderer view - `renderer/core-html-renderer/src/main/node`.
To run dev version on http://localhost:1234 execute next commands:

[source,sh]
----
; npm i
; npm start
----

Html renderer is based on Json Renderer so there is a prepared dataset (json) which represents all features available in Apiator.
It's located at `renderer/core-html-renderer/src/main/node/src/js/apiatorJsonStub.js` and is used by default in dev mode.
There is a task from root gradle project to regenerate this json:

[source,sh]
----
; # use wrapper version corresponding to your OS
; ./gradlew generate_stub
----

The generated stub can be committed into the repo as is without additional formatting to keep history of changes.

=== Documentation

Current documentation is written in Asciidoc with https://asciidoctor.org/[Asciidoctor] engine.
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference[Asciidoc syntax quick reference]

[source,shell]
----
; # run process to rebuild doc sources on change
; ./gradlew asciidoctor -t -p ./docs
; # the build result can be served in any way. F.e. via python dev web-server
; (cd ./docs/build/asciidoc/html5/ && python3 -m http.server --bind 127.0.0.1)
----