== Getting started

Apiator is built with JDK 11 so it's minimum required api of build tool-chain to run.
JDK (not JRE) is required.
The minimum level for the compiled classes of your project is JDK 8.
So you can build you project and run apiator with two independent JDK versions.

[#_getting_a_binary]
=== Getting a binary

Binary artifacts are hosted on https://search.maven.org/search?q=g:com.ainrif.apiator[Maven Central]

You can use it in you
link:https://docs.gradle.org/current/userguide/dependency_management.html#sub:maven_repo[gradle]
or
link:https://maven.apache.org/guides/mini/guide-multiple-repositories.html[maven]
project

* group: `com.ainrif.apiator`
* version: image:https://img.shields.io/maven-central/v/com.ainrif.apiator/core.svg?label=Maven%20Central&color=blue[version,link=https://search.maven.org/search?q=g:com.ainrif.apiator]
* artifacts: it is desirable to use the next set for quick start
** `core-html-renderer`
** `{multiply}-provider` corresponding to your web-framework
** `{multiply}-plugin-core-json-renderer` according to provider

=== How to run with ...

Apiator can be used in many ways: as library on classpath, gradle plugin, test dependency...
Good choice is to incorporate apiator into your build process to deliver documentation with application together.

==== Gradle plugin

Minimum requirement - Gradle 5.3

The Apiator Gradle plugin is published at https://plugins.gradle.org/plugin/com.ainrif.apiator[Gradle Portal].
So you have to add it to build script:

[source,groovy]
----
buildscript {
  repositories {
    mavenCentral()
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.ainrif.apiator:apiator-gradle-plugin:<version>"
  }
}

apply plugin: "com.ainrif.apiator"
----

After it Apiator plugin provides new `apiator` SourceSet to keep your main sources clean.

NOTE: You can ignore this SourceSet and place Apiator configs at main SourceSet for quick start.

To use `apiator` SourceSet create folder `apiator` at the same level with `main`.
This SourceSet have its own classpath which extends `main` and can be configured via `apiatorCompile` in gradle.
See the {github-dev}/gradle-plugin/test-gradle-plugin/build.gradle[build.gradle] in `testing-gradle-plugin` module.

The best choice is to apply Apiator plugin in module which classpath contains all web endpoints.
To pass link:#_configuration[configuration] you have to implement `ApiatorGradleRunner`
and specify its name at `apiator` task:

[source,groovy]
----
apiator {
    runnerClass = 'full.class.name.ApiatorRunner' // <1>
}
----

<1> Full name of the class which implements `ApiatorGradleRunner` and have default (or zero-arg) constructor

Class which implements `ApiatorGradleRunner` will be initialized and called for documentation generation.
In implemented method `ApiatorGradleRunner#execute(...)` you have to configure and run Apiator.

NOTE: Complete configuration examples can be found at `testing-gradle-plugin` module in classes
{github-dev}/gradle-plugin/test-gradle-plugin/src/apiator/java/testing/TestingJavaPluginApiatorConfig.java[TestingJavaPluginApiatorConfig]
for Java and
{github-dev}/gradle-plugin/test-gradle-plugin/src/apiator/groovy/testing/TestGroovyPluginApiatorConfig.groovy[TestGroovyPluginApiatorConfig]
for Groovy

==== As a library

Apiator can be used as a standard library.
Everything you need is to download all necessary libraries and run them in the same `classpath` with you endpoint classes.

NOTE: If you need to extend `classpath` at runtime you can do it with incubating functionality `Apiator#setExtraClassPath(URL[])`.
Extra `classpath` will be available during scanning and javadoc parsing.

[#_configuration]
=== Configuration

The main class of Apiator is `Apiator` 😉 and it can be configured via `ApiatorConfig`.

Let's say we are using one of JAX-RS web-frameworks (`jax-rs-provider`) and we want generate html view.

By default `ApiatorConfig` is set up to search for classes annotated with `com.ainrif.apiator.api.annotation.Api`.
So you must select only type of link:#_providers[web service provider] and type of link:#_renderers[renderer], f.e.:

[source,groovy]
----
ApiatorConfig config = new ApiatorConfig();
config.provider = new JaxRsProvider();
config.renderer = new CoreHtmlRenderer();

String html = new Apiator(config).render();
----

The result string will be a `html` which is "all in one" document so you can save it and serve from http server as is.

NOTE: More examples of configuration can be found at corresponding `*SmokeSpec`
{github-dev}/src/test/groovy/com/ainrif/apiator/test/smoke/CoreHtmlRendererSmokeSpec.groovy[CoreHtmlRendererSmokeSpec]